// <auto-generated />
namespace DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class mig1_message_table_adding : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig1_message_table_adding));
        
        string IMigrationMetadata.Id
        {
            get { return "202111152036314_mig1_message_table_adding"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
