// <auto-generated />
namespace DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class mig1_about_table_summary_adding : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig1_about_table_summary_adding));
        
        string IMigrationMetadata.Id
        {
            get { return "202111151501591_mig1_about_table_summary_adding"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
